name = "cloaker"
main = "cloaker-worker.js"
compatibility_date = "2024-01-01"

# Worker configuration
[env.production]
vars = { MAIN_APP_URL = "https://cranads.com", LOG_ENDPOINT = "https://cranads.com/api/logs/public", CAMPAIGN_WORKER_URL = "https://cloaker.maximillianfreakyads.workers.dev" }

# Development environment
[env.development]
vars = { MAIN_APP_URL = "http://localhost:8787", LOG_ENDPOINT = "http://localhost:8787/api/logs/public", CAMPAIGN_WORKER_URL = "http://localhost:8788" }

# Routes - uncomment and configure if you want a custom domain
# [[routes]]
# pattern = "cloaker.yourdomain.com/*"
# zone_name = "yourdomain.com"

# Deployment settings
[build]
command = ""

# Observability
[observability]
enabled = true